services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - ".:/app"
    env_file:
      - ./.env

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - api