name: CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images and push to Docker Hub
        run: |
          docker build -t tataran/penaly-server .
          docker build -t tataran/penaly-nginx ./nginx
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          docker push tataran/penaly-server
          docker push tataran/penaly-nginx
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Create env file'
      run: |
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo SERVER_ENDPOINT=${{ secrets.SERVER_ENDPOINT }} >> .env
        echo ORIGIN_1=${{ secrets.ORIGIN_1 }} >> .env
        echo ORIGIN_2=${{ secrets.ORIGIN_2 }} >> .env
        echo JWT_SECRET_ACCESS=${{ secrets.JWT_SECRET_ACCESS }} >> .env
        echo JWT_SECRET_REFRESH=${{ secrets.JWT_SECRET_REFRESH }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env

    - name: Generate deployment package
      run: zip -r ${{ github.run_id }}.zip . -x '*.git*'

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: test-server-3
        environment_name: Test-server-3-env
        region: ap-southeast-1
        version_label: ${{github.run_number}}
        deployment_package: ${{ github.run_id }}.zip